"""
InvestIQ AI — Shared / Public View Page
Accessible via: https://your-app.streamlit.app?token={public_token}
No login required. Read-only full dashboard.
"""

import streamlit as st
from styles.theme import apply_theme


def render_shared():
    apply_theme()

    # ── Get token from URL ─────────────────────────────────────────────────────
    token = st.query_params.get("token", "")

    if not token:
        _render_not_found("No share token provided.")
        return

    # ── Fetch public analysis ──────────────────────────────────────────────────
    if f"shared_{token}" not in st.session_state:
        with st.spinner("Loading shared analysis..."):
            from db.firestore import fetch_public_analysis
            result = fetch_public_analysis(token)
            st.session_state[f"shared_{token}"] = result
    else:
        result = st.session_state[f"shared_{token}"]

    if not result:
        _render_not_found("This analysis is not available or is no longer public.")
        return

    # ── Shared banner ──────────────────────────────────────────────────────────
    _render_shared_banner(result)

    # ── Full dashboard (read-only) ─────────────────────────────────────────────
    _render_shared_dashboard(result)

    # ── CTA at bottom ─────────────────────────────────────────────────────────
    _render_bottom_cta()


# ── SHARED BANNER ─────────────────────────────────────────────────────────────

def _render_shared_banner(result: dict):
    startup_name = result.get("startup_name", "Startup")
    created = result.get("created_at", "")

    date_display = ""
    if created:
        try:
            from datetime import datetime
            dt = datetime.fromisoformat(created.replace("Z", "+00:00"))
            date_display = dt.strftime("%B %d, %Y")
        except Exception:
            date_display = created[:10]

    st.markdown(f"""
    <div style="
        background:linear-gradient(135deg,
            rgba(0,212,255,0.06) 0%,
            rgba(108,99,255,0.06) 100%
        );
        border:1px solid rgba(0,212,255,0.2);
        border-radius:12px;
        padding:1rem 1.5rem;
        margin-bottom:1.5rem;
        display:flex;
        align-items:center;
        justify-content:space-between;
        flex-wrap:wrap;
        gap:0.8rem;
    ">
        <div style="display:flex; align-items:center; gap:0.8rem;">
            <div style="font-size:1.2rem;">🔗</div>
            <div>
                <div style="
                    font-size:0.65rem; color:#00D4FF;
                    text-transform:uppercase; letter-spacing:0.15em;
                    font-weight:700; margin-bottom:0.15rem;
                ">SHARED ANALYSIS — READ ONLY</div>
                <div style="font-size:0.82rem; color:#7B92B2;">
                    This investment report was generated by
                    <span style="color:#F0F6FF; font-weight:600;">InvestIQ AI</span>
                    {f'on {date_display}' if date_display else ''}
                </div>
            </div>
        </div>
        <div style="
            font-family:'Space Grotesk', sans-serif;
            font-weight:700;
            font-size:0.95rem;
            color:#F0F6FF;
        ">Invest<span style="
            background:linear-gradient(135deg,#00D4FF,#6C63FF);
            -webkit-background-clip:text;
            -webkit-text-fill-color:transparent;
        ">IQ</span> AI</div>
    </div>
    """, unsafe_allow_html=True)


# ── FULL DASHBOARD ─────────────────────────────────────────────────────────────

def _render_shared_dashboard(result: dict):
    from components.gauge import render_score_hero
    from components.radar import render_radar, render_score_bar_chart
    from components.score_cards import (
        render_four_score_cards,
        render_innovation_card,
        render_strengths_weaknesses,
        render_recommended_actions,
        render_executive_summary,
        render_agent_deep_dive,
    )
    from components.pdf_export import render_pdf_download_button

    startup_name = result.get("startup_name", "Startup")

    # Page header
    st.markdown(f"""
    <div class="page-header">
        <h1>📊 {startup_name}</h1>
        <p>
            {result.get('industry', '')}
            {'  ·  ' + result.get('funding_stage', '') if result.get('funding_stage') else ''}
            {'  ·  ' + result.get('business_model', '') if result.get('business_model') else ''}
        </p>
    </div>
    """, unsafe_allow_html=True)

    # ROW 1: Hero + bar chart
    col_gauge, col_right = st.columns([1.2, 1])
    with col_gauge:
        render_score_hero(result)
    with col_right:
        st.markdown("<div style='height:1.5rem'></div>", unsafe_allow_html=True)
        render_innovation_card(result)
        st.markdown("<div style='height:0.8rem'></div>", unsafe_allow_html=True)
        render_score_bar_chart(result, height=220)

    _divider()

    # ROW 2: Four score cards
    render_four_score_cards(result)

    _divider()

    # ROW 3: Radar + SW
    col_radar, col_sw = st.columns([1, 1.2])
    with col_radar:
        st.markdown("""
        <div style="
            font-size:0.65rem; color:#3A4F6A;
            text-transform:uppercase; letter-spacing:0.15em;
            font-weight:600; margin-bottom:0.5rem; text-align:center;
        ">5-DIMENSION RADAR</div>
        """, unsafe_allow_html=True)
        render_radar(result)
    with col_sw:
        render_strengths_weaknesses(result)

    _divider()

    # ROW 4: Actions
    render_recommended_actions(result)

    _divider()

    # ROW 5: Executive summary
    render_executive_summary(result)

    _divider()

    # ROW 6: Agent deep dive
    st.markdown("""
    <div style="
        font-size:0.65rem; color:#3A4F6A;
        text-transform:uppercase; letter-spacing:0.18em;
        font-weight:600; margin-bottom:0.8rem;
    ">AGENT DEEP DIVE — FULL ANALYSES</div>
    """, unsafe_allow_html=True)
    render_agent_deep_dive(result)

    _divider()

    # PDF export (available on shared view too)
    col_l, col_c, col_r = st.columns([1.5, 2, 1.5])
    with col_c:
        render_pdf_download_button(result)


# ── NOT FOUND ─────────────────────────────────────────────────────────────────

def _render_not_found(message: str = "Analysis not found."):
    st.markdown(f"""
    <div style="
        text-align:center;
        padding:5rem 2rem;
        max-width:480px;
        margin:0 auto;
    ">
        <div style="font-size:3rem; margin-bottom:1rem;">🔒</div>
        <div style="
            font-size:1.2rem;
            font-weight:700;
            color:#F0F6FF;
            margin-bottom:0.6rem;
            font-family:'Space Grotesk', sans-serif;
        ">Report Not Available</div>
        <div style="font-size:0.88rem; color:#7B92B2; line-height:1.6;">
            {message}
        </div>
    </div>
    """, unsafe_allow_html=True)
    _render_bottom_cta()


# ── BOTTOM CTA ────────────────────────────────────────────────────────────────

def _render_bottom_cta():
    st.markdown("""
    <div style="
        text-align:center;
        padding:2.5rem 1rem;
        background:linear-gradient(135deg,
            rgba(0,212,255,0.04) 0%,
            rgba(108,99,255,0.04) 100%
        );
        border:1px solid #1A2F4A;
        border-radius:14px;
        margin-top:2rem;
    ">
        <div style="
            font-family:'Space Grotesk', sans-serif;
            font-weight:700;
            font-size:1.3rem;
            color:#F0F6FF;
            margin-bottom:0.5rem;
        ">
            Invest<span style="
                background:linear-gradient(135deg,#00D4FF,#6C63FF);
                -webkit-background-clip:text;
                -webkit-text-fill-color:transparent;
            ">IQ</span> AI
        </div>
        <div style="font-size:0.85rem; color:#7B92B2; margin-bottom:1.2rem;">
            Multi-agent AI investment intelligence — free forever
        </div>
        <div style="font-size:0.78rem; color:#3A4F6A;">
            6 specialist AI agents · Structured scoring · PDF export · Shareable reports
        </div>
    </div>
    """, unsafe_allow_html=True)

    st.markdown("<div style='height:1rem'></div>", unsafe_allow_html=True)

    col_l, col_c, col_r = st.columns([1.5, 2, 1.5])
    with col_c:
        if st.button("🔍  Analyze Your Own Startup →", use_container_width=True, type="primary"):
            # Clear token and go to analyze
            st.query_params.clear()
            st.session_state.current_page = "analyze"
            st.rerun()


def _divider():
    st.markdown("""
    <div style="
        height:1px;
        background:linear-gradient(90deg,transparent,#1A2F4A,transparent);
        margin:1.8rem 0;
    "></div>
    """, unsafe_allow_html=True)